# _config.yml
title: Mateo Armijo's Website
description: Occidental College Student Mateo Armijo
url: "https://MateoArm.github.io" 
baseurl: "" 

author:
  name: Mateo Armijo
  email: armijo@oxy.edu
  github: MateoArm

markdown: kramdown
# REMOVE THIS LINE: theme: jekyll-theme-lanyon

# Lanyon theme options
lanyon:
  sidebar: true  
  theme: dark
