# _config.yml
title: Mateo Armijo
description: "I don't know everything, I just know what I know" -Tsubasa Hanekawa
url: "https://MateoArm.github.io" 
baseurl: "" 

author:
  name: Mateo Armijo
  email: armijo@oxy.edu
  github: MateoArm

markdown: kramdown

# Lanyon theme options - use the darkest option
lanyon:
  sidebar: true  
  theme: dark
